name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
    container: ros:jazzy-ros-base
    steps:
      - uses: actions/checkout@v3

      - name: build and test
        shell: bash
        run: |
          #ワークスペース構造の構築
          mkdir -p /root/ros2_ws/src
          cp -r src/mypkg /root/ros2_ws/src/
          cp -r src/system_msgs /root/ros2_ws/src/

          #依存ツールのインストール
          apt-get update
          
          apt-get install -y python3-colcon-common-extensions

          #依存関係の解決
          cd /root/ros2_ws
          rosdep update
          # --from-paths で src 内の全パッケージの依存関係をインストール
          rosdep install -i --from-path src --rosdistro jazzy -y

          #テストの実行
          chmod +x src/mypkg/test/test.bash
          ./src/mypkg/test/test.bash /root
